### ISSUE TITLE
Create cheatsheet for students

### ISSUE THREAD

**Issue by bridgethillyer** [ClojureBridge/curriculum#100]
Create a cheatsheet with key syntax, function names, etc. that students are using in the exercises. A simple one-pager that could be printed out and used by students to help guide them during the exercises.

**Comment by kpfell** [comment]
For those following along, it looks like we'll be merging https://github.com/ClojureBridge/curriculum/pull/124 after experimenting with fonts a bit.

So, this issue seems to be covered for the moment! :tada:

**Comment by rubygeek** [comment]
I sent Bridget a copy with the fonts bolded, my printer refuses to speak to
my mac at the moment!

On Fri, Feb 6, 2015 at 7:50 PM, Katherine Fellows <notifications@github.com>
wrote:

> For those following along, it looks like we'll be merging #124
> <https://github.com/ClojureBridge/curriculum/pull/124> after
> experimenting with fonts a bit.
>
> So, this issue seems to be covered for the moment! [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClojureBridge/curriculum/issues/100#issuecomment-73344085>
> .
>



-- 
http://blog.rubygeek.com - my blog
http://www.linkedin.com/in/nolastowe - my linkedin profile
http://www.twitter.com/rubygeek - my twitter
http://github.com/rubygeek - my code

**Comment by kpfell** [comment]
@rubygeek \o/

A few of us were planning on working on the curriculum tomorrow morning, so I wanted to add notes to any open issues. ;)
