### ISSUE TITLE
Remove Heroku setup from installfest instructions

### ISSUE THREAD

**Issue by bridgethillyer** [ClojureBridge/curriculum#117]
Since we no longer deploy a web app, the Heroku setup can be removed (or, at least, marked as optional) from the installfest instructions. Note: there are multiple versions of the instructions, so need to take them out from multiple places.

**Comment by duelinmarkers** [comment]
We're looking at merging these changes for Austin ClojureBridge. The only additional work that seems to be needed is providing git installation instructions (except for OS X, which already has them). 

The Ubuntu instructions are easy. Windows is a bit trickier. 

On the [git-scm book site](http://git-scm.com/book/en/v2/Getting-Started-Installing-Git#Installing-on-Windows), they suggest that [GitHub for Windows](https://windows.github.com/) may be a better way to go than the plain [git-scm Windows download](http://git-scm.com/download/win). Does anyone know if that's good advice? I like the sound of "solid credential caching and sane CRLF settings."

**Comment by duelinmarkers** [comment]
My WIP is here: https://github.com/AustinClojure/curriculum/tree/rm-heroku -- currently I'm pointing at the git-scm download for Windows.

**Comment by kpfell** [comment]
@duelinmarkers Did you want to open a PR for the changes from Austin Clojure's hack day? I see a couple relevant commits [here](https://github.com/AustinClojure/curriculum/commits/master), in particular.

**Comment by duelinmarkers** [comment]
If you think they look worth merging, I'll do that. (I think they are.)

**Comment by kpfell** [comment]
Fixed via https://github.com/ClojureBridge/curriculum/pull/126.
