### ISSUE TITLE
Update CONTRIBUTING.md with information about updating slides

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#125]
When folks update the curriculum, the slides usually end up falling out of date, potentially requiring someone to manually go back through and correct them before each workshop.

We should probably have a section in [CONTRIBUTING.md](https://github.com/ClojureBridge/curriculum/blob/master/CONTRIBUTING.md) that addresses this--possibly just a section that says tl;dr "If you update the curriculum, your PR must also address updates in the slides"?

**Comment by kpfell** [comment]
In particular, this would keep https://github.com/ClojureBridge/curriculum/issues/90 from happening repeatedly.

**Comment by yokolet** [comment]
Since slides and markdown files are exactly the same now, we don't need an update guide anymore.
Downside is editing curriculum's markdown files got a bit complicated. However, I added EDITING-CURRICULUM.md as a guide, so people will understand what they should care about while editing.
