### ISSUE TITLE
Add a link to what a BigInt is?

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#130]
In the "[Arithmetic](https://github.com/ClojureBridge/curriculum/blob/master/outline/intro.md#arithmetic)" section, there's currently a reference to BigInts:
```
(* 8 1/4)     ;=> 2   ;; this produces 2N which means 2 is a BigInt.
```
BigInts are pretty far out of scope for a beginner-level workshop. Any feedback as to how we want to adjust this line?

**Comment by bridgethillyer** [comment]
I think avoiding the mention of BigInt altogether would be the way to go. But anyone who runs this will see the "2N" result and be confused. I think that rephrasing the explanation would be preferable. Here's a suggestion, but someone else can probably do better than this.
```
(* 8 1/4)     ;=> 2N     ;; just read this as 2 - the N is not related to anything we're doing
```
Or just get rid of this example altogether.

**Comment by kpfell** [comment]
Yeah, the reason why I asked was that I didn't particularly want a reference to BigInt at all, but it's in the curriculum, so perhaps it was put there for a reason?

I'd vote for removing the reference entirely, as we're not doing anything that requires multiplying integers by ratios in the exercises (we used decimals instead of ratios). Leaving a note like you mentioned above--reworded or not--would require going back at some point in the curriculum and explaining what BigInts are, and that's also pretty far out of scope, in my opinion.

**Comment by davidchambers** [comment]
I too am in favour of removing this example.
