### ISSUE TITLE
Remove expectations from curriculum

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#140]
_Note: Feel free to suggest other titles for this PR, as it's probably pretty unclear as is._

It would probably be helpful for us to go through the curriculum and remove all instances of "You can probably guess what this is," "As you might expect," etc.--essentially, any phrase that implies the reader knows something, already. Then, we should rephrase those instances to focus on actions the reader should take.

For example, in [intro.md](https://github.com/ClojureBridge/curriculum/blob/2f7c4a95e3648aa79103a667784688032a1b12ac/outline/intro.md), there's a line that reads

> The first thing you notice are parentheses, probably.

That could be rephrased to

> Notice the parentheses.

which shifts focus from what the reader _knows_ to what the reader _should do._

**Comment by davidchambers** [comment]
I like this idea. Another benefit is that sentences become shorter and clearer.

**Comment by bridgethillyer** [comment]
That's a very thoughtful suggestion. I think it's a great idea.

**Comment by yokolet** [comment]
Updated as in the suggestion, http://clojurebridge.github.io/curriculum/outline/intro.html#/3 .
If you find this sort of expectations, open another issue. I'm going to close this one.
