### ISSUE TITLE
Leiningen Windows Installer Issues doesn't download lein.bat on Windows 8

### ISSUE THREAD

**Issue by ajuckel** [ClojureBridge/curriculum#142]
On Windows, some users had issues with the Leiningen Windows Installer.  After running the installer, lein.bat was missing from the install directory, and curl.exe from the install directory would fail to download any file with:

error:0307A071:bignum routines:BN_rand_range:too many iterations.

Skipping the Leiningen Windows Installer, and instead downloading lein.bat from leiningen.org and running self-installer was successful, as long as all traces of the .lein directory from Leiningen Windows Installer were first deleted.

**Comment by duelinmarkers** [comment]
This may be what one of the students at ATX ClojureBridge hit yesterday. If downloading lein.bat works, it seems like a good idea not to depend on any additional projects and just do the simplest thing.

**Comment by yokolet** [comment]
I added this info to troubleshooting section, https://github.com/ClojureBridge/curriculum/blob/gh-pages/outline/setup_win8.md. 
Thanks for the report!
