### ISSUE TITLE
Add "'git' is not recognized as an internal or external command" to install troubleshooting

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#147]
After going through the git instructions in the install directions for Windows 8, one attendee at ClojureBridge Austin encountered this error:

http://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command

That should be added to the appropriate troubleshooting section.

**Comment by lindboe** [comment]
I ran into this on Windows 7 too, so it should get added there. Working on it.

**Comment by yokolet** [comment]
This issue should be closed since the #157 has been merged and both win7/8 setup instructions have this info.
Thanks for working on this!
