### ISSUE TITLE
"Infix vs. prefix" slide is slightly confusing

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#148]
After hearing that Clojure used prefix notation vs. infix notation, then seeing the [relevant slide](https://github.com/ClojureBridge/curriculum/blob/master/slides/module1.html), one student gathered that you could use _both_ notations in Clojure, because they were both presented on the slide with the same amount of emphasis.

We should add a note to the slide explicitly saying that the infix example is for JavaScript, etc., whereas the prefix notation is for Clojure.

**Comment by yokolet** [comment]
I'm going to close this issue since all are in the current slides.
