### ISSUE TITLE
Slides vs markdown?

### ISSUE THREAD

**Issue by nathanielksmith** [ClojureBridge/curriculum#158]
What's the connection between the slides and the markdown of the curriculum? Currently they do not match up and there are some errors in the markdown as a result.

Where should I be fixing those inconsistencies?

**Comment by davidchambers** [comment]
Neither document is generated from the other. Unfortunately changes should be made to both documents.

**Comment by kpfell** [comment]
What @davidchambers said.

The relationship between the slides and the curriculum Markdown is that they should ultimately convey the same information. We're in the process of re-syncing them up, after the slides fell behind (https://github.com/ClojureBridge/curriculum/issues/90).

tl;dr They're out of sync starting at Module 4, and it would most excellent if you submitted more PRs to fix #90. ;)

**Comment by yokolet** [comment]
Over the weekend, I setup gh-pages using jekyll and moved all contents to gh-pages. Now, markdown files in outline directory are rendered as slides. There's no difference between markdown files and slides.

I'm going to close this issue.
