### ISSUE TITLE
Make gh-pages branch default?

### ISSUE THREAD

**Issue by danielcompton** [ClojureBridge/curriculum#178]
GitHub lets you change the default branch. Would it be helpful to make the default branch `gh-pages`, as that is where all of the new content and curriculum goes?

**Comment by yokolet** [comment]
@danielcompton thanks for the suggestion. I didn't know there's such setting. I tested using my personal repository and looked good. I'll change the default branch, so that people can go directly to the gh-pages branch.

**Comment by yokolet** [comment]
Done.
