### ISSUE TITLE
LightTable instarepl depreciated

### ISSUE THREAD

**Issue by practicalli-johnny** [ClojureBridge/curriculum#187]
The setup instructions for LightTable say to use its Instarepl as the first way to test LightTable is working, however the Clojure Instarepl is now a plugin that is not included by default and therefore no Instarepl command is available without installing the plugin.

Further, the Clojure Instarepl plugin does not have a maintainer and is not used by the core development team of LightTable.  

I suggest that the test to see if LightTable is working would just be to run the project, so the content mentioning the Instarepl should be removed.

**Comment by yokolet** [comment]
Hm,,, it may be time to switch to Nightcode. Berlin team has already done that. In any case, Instarepl part should go away.

**Comment by k4y3ff** [comment]
+1 to moving to Nightcode, at this point.

**Comment by yokolet** [comment]
We switched to use Nightcode 2.1.0. Main curriculum and other materials were updated. Given that, I'm going to close this issue. Thanks for the report! Good luck on your London chapter, @jr0cket !
