### ISSUE TITLE
proposal: delete master branch

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/curriculum#200]
Shall we delete the **master** branch? I'd find it less confusing to only have the **gh-pages** branch.

**Comment by plexus** [comment]
makes sense, no objection here.

**Comment by yokolet** [comment]
Ah, I've never thought "delete master branch." As far as I googled, we can do that. Our gh-pages branch is already a default. So, it should be easy.

👍

**Comment by davidchambers** [comment]
Done.
