### ISSUE TITLE
Instructions to teachers on how to use curriculum

### ISSUE THREAD

**Issue by bridgethillyer** [ClojureBridge/curriculum#45]
Add file to curriculum and link to it from README with instructions to teachers on how to use curriculum

**Comment by kpfell** [comment]
As it's been another two, months, I'm now seconding the "this is a very important outstanding issue" comment from @bridgethillyer. It would be great for us to start working on this!

**Comment by bridgethillyer** [comment]
@kpfell, @rubygeek - maybe we can start taking notes about how we approach the curriculum for the Austin workshop. Then we can compile our notes and publish them as a first draft of a teacher's guide. Sound possible?

**Comment by kpfell** [comment]
Sure! That sounds like a great plan.

**Comment by rubygeek** [comment]
Sound like a plan

**Comment by bridgethillyer** [comment]
Started a first draft of this in my repo. I plan on doing my best to take notes while I prepare and during the  workshop. If y'all want to do any of that, too, @kpfell and @rubygeek , that would be great: https://github.com/bridgethillyer/curriculum/blob/teach-guide/TEACHING.md

**Comment by bridgethillyer** [comment]
I actually managed to write some things down after the workshop! It would be a huge help if you could add anything - even little tidbits would be great! @kpfell and @rubygeek 

https://github.com/bridgethillyer/curriculum/blob/teach-guide/TEACHING.md

**Comment by yokolet** [comment]
Hi all, 
This issue should be closed since the doc is already here, https://github.com/ClojureBridge/curriculum/blob/master/TEACHING.md

Thanks @bridgethillyer, the doc is awesome.
