### ISSUE TITLE
heroku keys:add missing for WIndows 7 & 8 install instructions

### ISSUE THREAD

**Issue by eah13** [ClojureBridge/curriculum#74]
I needed to add 

```
heroku keys:add %USERPROFILE%/.ssh/id_rsa.pub
```
to the instructions to get the student up and running.  Otherwise Heroku didn't know who they were.  `heroku keys:add` prolly works for most situations.

Happy to add this if it's helpful.  Looks like both windows installs are missing them.

**Comment by kpfell** [comment]
Given that we're currently removing Heroku from the curriculum (as per https://github.com/ClojureBridge/curriculum/issues/117), I'm closing this issue for the time being.
