### ISSUE TITLE
Fix to lein repl problems for windows 7 student

### ISSUE THREAD

**Issue by eah13** [ClojureBridge/curriculum#75]
Student with WIndows 7 kept getting errors when she ran `lein repl` that had this in them:

```
Address family not supported by protocol family: connect
```
lein couldn't download its stuff.  Found the resolution here:
http://stackoverflow.com/a/21383865

A program called Relevant Knowledge was somehow blocking the traffic.  Possibly spyware.  Anyways, uninstalling it (with her permission- she hadn't heard of it) fixed the problem.  Documenting for posterity- not sure whether a troubleshooting section would be helpful for future groups.  Happy to write something up if there's a place that makes sense.

**Comment by yokolet** [comment]
This issue should be closed since the pull request has been merged.
