### ISSUE TITLE
Update OS X setup with workaround for 10.6.8

### ISSUE THREAD

**Issue by bridgethillyer** [ClojureBridge/curriculum#78]
Whatever was keeping Light Table from working on OS X 10.6.8 seems to have been resolved. So if you do the following, LT should be able to run:

"remov[e] key "LSMinimumSystemVersion" from Info.plist"

**Comment by yokolet** [comment]
The troubleshooting section has been added to https://github.com/ClojureBridge/curriculum/blob/gh-pages/outline/setup_osx.md .
I'm going to close this issue.
