### ISSUE TITLE
Opening file in Light Table from command line?

### ISSUE THREAD

**Issue by kpfell** [ClojureBridge/curriculum#87]
A few times at the SF workshop, the curriculum/slides/TAs guided students to `cd` into a certain directory--leading to the natural question, "How do I open this file/directory in Light Table from the command line?"

We should either have the Light Table equivalent of `subl` added to the installfest, or rewrite the sections that refer to `cd`ing into directories in the curriculum.

**Comment by seancorfield** [comment]
FWIW, on Mac OS X, the following "just works":

    /Applications/LightTable/light myfile.clj

If LightTable is not open, it will open it and load the file. If it is open, it will load the file.

**Comment by kpfell** [comment]
An update, for anyone who wants to work on this issue: Probably, it would make sense to add information about one of the two above commands to the installfest instructions--maybe in the "Troubleshooting" section mentioned in https://github.com/ClojureBridge/curriculum/issues/98 ?

Also, adding the information for all of the operating systems linked to [here](https://github.com/ClojureBridge/curriculum/blob/master/outline/setup.md) would be helpful, if possible.

**Comment by daveyarwood** [comment]
I use Light Table on OS X, and the following works great for opening files and folders from the command line:

    open -a /Applications/LightTable/LightTable.app path/to/file.clj

You could easily add an alias for this so that you can open files by just typing `light-table /path/to/file`. 

[Apparently](https://groups.google.com/forum/#!topic/light-table-discussion/IhebCaPwou8) for the Linux version of Light Table, you can already open files by typing `light-table path/to/file.clj`.

I'd be happy to make a PR to add a step of aliasing `open -a /Applications/LightTable/LightTable.app` to `light-table` to the OS X install-fest instructions. Then the curriculum can just say, when appropriate, e.g. "Open the project folder in Light Table by typing `light-table /some/project`.

**Comment by kpfell** [comment]
> I'd be happy to make a PR to add a step of aliasing open -a /Applications/LightTable/LightTable.app to light-table to the OS X install-fest instructions.

Yes, that would be helpful! Though, we'd need to update the Linux and Windows docs simultaneously, as well?

> Then the curriculum can just say, when appropriate, e.g. "Open the project folder in Light Table by typing light-table /some/project.

I should note that we generally avoid opening things from the command line in the actual curriculum, because people in many of the workshops aren't familiar with the command line, and that's kind-of a [separate beast](http://cli.learncodethehardway.org/book/)? This step would be more for intermediate-level folks, as well as optional.

**Comment by daveyarwood** [comment]
Ah, I see! That makes sense. So maybe it's best left as a minor note in the setup instructions, and note that it's optional.

Linux should be good-to-go, I think. I haven't verified this, but it appears that when you install Light Table on a Linux machine, it gives you an executable script called `light-table`, which can take a file/folder argument.

I didn't think about Windows... I have no idea how that works! From what I can tell, there is a LightTable.exe that you double click to open it, but I'm not really familiar with using Cygwin, PowerShell, etc., so not sure how a typical Windows developer would go about opening files from the command line.

**Comment by kpfell** [comment]
Bah, yeah... I don't actually have access to a Windows machine, soooooo ¯\_(ツ)_/¯

Though, you could totally still submit the Linux + OS X PR! And we could leave this issue open in the meantime?

**Comment by daveyarwood** [comment]
PR submitted! I vote that we close this issue and we can always create a new issue if the question ever comes up in the future about how to open files in LT from the command line in a particular Windows shell.

Also, here's your other arm, lol: \\

**Comment by seancorfield** [comment]
@daveyarwood did you try the command I suggested earlier in this thread:

    /Applications/LightTable/light myfile.clj

That seems simpler than using `open`.

**Comment by daveyarwood** [comment]
@seancorfield when I try that command, the file does open up in LightTable, however I also see this error message in the terminal:

    [19531:0421/182309:ERROR:breakpad_mac.mm(234)] Breakpad initializaiton failed

It also blocks the terminal until I hit Ctrl-C.

**Comment by seancorfield** [comment]
Ah, good to know. OK, sounds like `open` is the better choice. Thanks!

**Comment by yokolet** [comment]
The pull request was merged and the updated document is, https://github.com/ClojureBridge/curriculum/blob/gh-pages/outline/setup_osx.md 
I'm going to close this issue.

**Comment by daveyarwood** [comment]
Hi again -- I just realized I made a dumb mistake and left the word "alias" out of the command to create the "light-table" alias in OSX... sorry about that! Another PR is on its way.
