### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by kwistens** [ClojureBridge/curriculum#88]
Locally, everything is running just fine, but I keep getting an application error when I run `heroku open` as instructed in ["Putting Your Application Online"](https://github.com/clojurebridge-sf/curriculum/blob/master/outline/deploy.md)

Things I've tried already:
* In project.clj, updated Lein with `:min-lein-version "2.0.0"` as instructed on [heroku dev center](https://devcenter.heroku.com/articles/clojure-support)
* In web.clj requirements, added `[hiccup.form :as form]` and `[ring.adapter.jetty :as ring]`
* In project.clj, added `:main ^:skip-aot global-growth.web`
* In web.clj, added  `(defn -main [] (ring/run-jetty #'main-routes {:port 8080 :join? false})`

There was also talk of this being an issue with Procfile (there isn't one?), but I'm not sure what's going on.  Any ideas?  Let me know if you'd like me to copy in any of my heroku logs.

Related: Is there recommended documentation on clojure app deployment via github.io?

Thanks for all your help in advance! :smile:

**Comment by kpfell** [comment]
Looks like this issue was resolved a long while ago, but the issue remains open.

Closing it now!

**Comment by kariannemah** [comment]
@kpfell :+1: Thanks! Hope all is well.
